# Generated by Django 2.1 on 2018-09-19 19:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20180916_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 21, 19, 16, 11, 386375, tzinfo=utc)),
        ),
    ]
