# Generated by Django 2.1 on 2018-10-07 06:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_auto_20181006_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 9, 6, 29, 13, 696134, tzinfo=utc)),
        ),
    ]
